---
- name: All hosts up-to-date
  hosts: local
  become: true
  vars:
    user: "{{ lookup('env', 'USER') }}"
    pacman:
      - base-devel
      - git
      - wget
      - github-cli
      - fcitx5-im
      - fcitx5-mozc
      - btop
      - nautilus
      - fish
      - ranger
      - xclip
      - python
      - curl
      - unzip
      - ripgrep
      - procps
      - gcc
      - nodejs
      - lazygit
      - playerctl
      - emacs
      - krita
      - jdk-openjdk
      - efibootmgr
      - gparted
      - mangohud
      - go
      - openvpn
      - chromium
      - file-roller
      - qpwgraph
      - scrcpy
      - sqlitebrowser
      - clang
      - cmake
      - ninja
      - proton-vpn-gtk-app
      - ttf-jetbrains-mono-nerd
      - noto-fonts-cjk
      - android-tools
      - openvpn
      - wireguard-tools
      - networkmanager
      - network-manager-applet
      - ttf-liberation
      - linux-headers
      - copyq
      - python-pynvim
      - tree
      - kitty
      - python-pip
      - wine-staging
      - firejail
      - firetools
      - pipewire
      - pipewire-pulse
      - pipewire-audio
      - wireplumber
      - cpupower
    aur:
      - vscodium-bin
      - floorp-bin
      - anki-bin
      - qdirstat-bin
      - sunshine
      - flutter
      - dart
      - android-sdk
      - android-sdk-platform-tools
      - android-sdk-cmdline-tools-latest
      - android-sdk-build-tools-35
      - android-platform-35
      - jdownloader2
  pre_tasks:
    - name: Get user UID and GID
      ansible.builtin.getent:
        database: passwd
        key: "{{ user }}"
      register: user_info
      failed_when: user_info.ansible_facts.getent_passwd[user] is not defined

    - name: Get user group information
      ansible.builtin.getent:
        database: group
        key: "{{ user }}"
      register: group_info
      failed_when: group_info.ansible_facts.getent_group[user] is not defined
  tasks:

    - name: Create aur_builder user for AUR operations
      user:
        name: aur_builder
        state: present

    - name: Allow aur_builder to run pacman without password
      lineinfile:
        path: /etc/sudoers.d/aur_builder-allow-to-sudo-pacman
        state: present
        line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
        validate: '/usr/sbin/visudo -cf %s'
        create: yes

    - name: Ensure [multilib] section exists in pacman.conf
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        marker: "# {mark} ANSIBLE MANAGED BLOCK - multilib"
        insertafter: EOF
        create: false
      register: multilib_section

    - name: Synchronize pacman database
      become: true
      community.general.pacman:
        update_cache: true
      when: multilib_section.changed

    - name: Install package
      community.general.pacman:
        name: "{{ pacman }}"
        state: present

    - name: Install aur packages
      include_tasks:
        file: install_aurpackages.yml
        apply:
          become: yes
          become_user: aur_builder
      loop: "{{ aur }}"

    - name: Install Android NDK version 26.3.11579264 if not present
      block:
        - name: Check if NDK source.properties exists
          ansible.builtin.stat:
            path: /opt/android-sdk/ndk/26.3.11579264/source.properties
          register: ndk_stat

        # バージョンが固定されているのは問題である可能性がある
        - name: Install NDK if source.properties is missing
          ansible.builtin.command:
            cmd: /opt/android-sdk/cmdline-tools/latest/bin/sdkmanager "ndk;26.3.11579264"
          when: not ndk_stat.stat.exists
          register: sdkmanager_result
          changed_when: sdkmanager_result.rc == 0

        - name: Ensure correct ownership of NDK directory
          ansible.builtin.file:
            path: /opt/android-sdk/ndk/26.3.11579264
            owner: "{{ user }}"
            group: "{{ user }}"
            recurse: yes
            state: directory
          when: sdkmanager_result.changed

    - name: Ensure PipeWire and WirePlumber services are enabled for the user
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        scope: user
        state: started
      loop:
        - pipewire.service
        - pipewire-pulse.service
        - wireplumber.service
      become: false
      become_user: "{{ user }}"

    #設定がある場合スキップすることで高速化可能
    - name: Create PipeWire configuration directory for the user
      ansible.builtin.file:
        path: "/home/{{ user }}/.config/pipewire/pipewire.conf.d"
        state: directory
        mode: '0755'
      become: false
      become_user: "{{ user }}"

    - name: Create PipeWire null sink configuration
      ansible.builtin.copy:
        content: |
          context.objects = [
            {
              factory = adapter
              args = {
                factory.name = support.null-audio-sink
                node.name = my-sink
                media.class = Audio/Sink
                object.linger = true
                audio.position = [ FL FR ]
                monitor.channel-volumes = true
                monitor.passthrough = true
              }
            }
          ]
        dest: "/home/{{ user }}/.config/pipewire/pipewire.conf.d/20-link-null-sink.conf"
        mode: '0644'
      become: false
      become_user: "{{ user }}"
      notify: Restart PipeWire services

    - name: Add system variable to .xprofile
      ansible.builtin.lineinfile:
        path: "/home/{{ user }}/.xprofile"
        line: "{{ item }}"
        state: present
        create: yes
        mode: '0755'
      loop:
        - '#!/bin/sh'
        - 'fcitx5 -d'
        - 'export GTK_IM_MODULE=fcitx'
        - 'export QT_IM_MODULE=fcitx'
        - 'export XMODIFIERS=@im=fcitx'
      become: false
      become_user: "{{ user }}"

    - name: Add system variable to .bashrc
      blockinfile:
        path: "/home/{{ user }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z "${BASH_EXECUTION_STRING}" ]]; then
            shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=""
            exec /usr/bin/fish $LOGIN_OPTION
          fi
        state: present

    - name: Ensure EDITOR is set in /etc/environment
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: 'EDITOR=nvim'
        state: present
        create: yes
      register: env_result
      changed_when: env_result.changed

    - name: Enable and start NetworkManager
      ansible.builtin.systemd_service:
        name: NetworkManager.service
        enabled: true
        state: started

    - name: Change CPU governor to performance for all cores
      lineinfile:
        path: /etc/default/cpupower
        state: present
        line: 'governor=performance'
        create: yes

    - name: Create CopyQ autostart desktop entry
      copy:
        dest: /etc/xdg/autostart/copyq.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=CopyQ
          Exec=copyq
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Comment=Clipboard manager with advanced features
        mode: '0644'
      become: yes

    - name: Create sunshine autostart desktop entry
      copy:
        dest: /etc/xdg/autostart/sunshine.desktop
        content: |
          [Desktop Entry]
          Type=Application
          Name=Sunshine
          Exec=sh -c "sleep 3 && sunshine"
          Hidden=false
          NoDisplay=false
          X-GNOME-Autostart-enabled=true
          Comment=Clipboard manager with advanced features
        mode: '0644'
      become: yes

    - name: Check ownership of /opt/flutter
      ansible.builtin.stat:
        path: /opt/flutter
      register: flutter_stat
    - name: Check ownership of /opt/android-sdk
      ansible.builtin.stat:
        path: /opt/android-sdk
      register: android_sdk_stat
    - name: Check ownership of /opt/dart-sdk
      ansible.builtin.stat:
        path: /opt/dart-sdk
      register: dart_sdk_stat

    - name: Change ownership of /opt/flutter
      ansible.builtin.file:
        path: /opt/flutter
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
        state: directory
      when: flutter_stat.stat.uid != (user_info.ansible_facts.getent_passwd[user][2] | int)
      register: flutter_ownership

    - name: Change ownership of /opt/android-sdk
      ansible.builtin.file:
        path: /opt/android-sdk
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
        state: directory
      when: android_sdk_stat.stat.uid != (user_info.ansible_facts.getent_passwd[user][2] | int)
      register: android_sdk_ownership

    - name: Change ownership of /opt/dart-sdk
      ansible.builtin.file:
        path: /opt/dart-sdk
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
        state: directory
      when: dart_sdk_stat.stat.uid != (user_info.ansible_facts.getent_passwd[user][2] | int)
      register: dart_sdk_ownership

  handlers:
    - name: Restart PipeWire services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        scope: user
      loop:
        - pipewire.service
        - pipewire-pulse.service
        - wireplumber.service
      become: false
      become_user: "{{ user }}"

    - name: Reload systemd
      ansible.builtin.systemd:
        daemon_reload: yes
