- name: Check gwe settings
  block:
    - name: Check state of nvidia_tdp_service
      stat:
        path: /etc/systemd/system/nvidia-tdp.service
      register: nvidia_tdp_service_stat

    - name: Check state of nvidia_tdp_timer
      stat:
        path: /etc/systemd/system/nvidia-tdp.timer
      register: nvidia_tdp_timer_stat

- name: Set gwe settings
  block:
    - name: Create nvidia-tdp.service unit file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Set NVIDIA power limit

          [Service]
          Type=oneshot
          ExecStartPre=/usr/bin/nvidia-smi -pm 1
          ExecStart=/usr/bin/nvidia-smi -pl 100
        dest: /etc/systemd/system/nvidia-tdp.service
        owner: root
        group: root
        mode: '0644'
      notify: Reload systemd

    - name: Create nvidia-tdp.timer unit file
      ansible.builtin.copy:
        content: |
          [Unit]
          Description=Timer for setting NVIDIA power limit

          [Timer]
          OnBootSec=5
          Unit=nvidia-tdp.service

          [Install]
          WantedBy=timers.target
        dest: /etc/systemd/system/nvidia-tdp.timer
        owner: root
        group: root
        mode: '0644'
      notify: Reload systemd

    - name: Enable and start nvidia-tdp.timer
      ansible.builtin.systemd:
        name: nvidia-tdp.timer
        enabled: yes
        state: started
  when: nvidia_tdp_service_stat.changed and nvidia_tdp_timer_stat.changed

- name: Add user to gamemode group
  user:
    name: "{{ user }}"
    groups: gamemode
    append: yes
  become: yes

- name: Ensure ext4 filesystem is mounted
  block:
    - name: Ensure mount point directory exists
      file:
        path: /run/media/"{{ user }}"/49538b9d-fe29-460b-a955-6edece14ec80
        state: directory
        owner: "{{ user }}"
        group: users
        mode: '0755'
    - name: mount ext4 filesystem
      mount:
        path: /run/media/"{{ user }}"/49538b9d-fe29-460b-a955-6edece14ec80
        src: UUID=49538b9d-fe29-460b-a955-6edece14ec80
        fstype: ext4
        opts: defaults
        state: mounted
  become: yes

- name: Create gwe autostart desktop entry
  copy:
    dest: /etc/xdg/autostart/gwe.desktop
    content: |
      [Desktop Entry]
      Type=Application
      Name=GreenWithEnvy
      Exec=sh -c "sleep 3 && gwe"
      Hidden=false
      NoDisplay=false
      X-GNOME-Autostart-enabled=true
    mode: '0644'
  become: yes
