---
- name: All hosts up-to-date
  hosts: all
  become: true
  vars:
    pacman:
      - base-devel
      - git
      - wget
      - github-cli
      - btop
      - fish
      - ranger
      - python
      - python-pip
      - curl
      - unzip
      - ripgrep
      - procps
      - gcc
      - nodejs
      - jdk-openjdk
      - clang
      - cmake
      - ninja
      - ttf-jetbrains-mono-nerd
      - tree
      - fastfetch
      - neovim
      - uv

  tasks:
    - name: Install package
      community.general.pacman:
        name: "{{ pacman }}"
        state: present

    - name: Change default shell to Fish for root
      user:
        name: root
        shell: /usr/bin/fish
