- name: All hosts up-to-date
  hosts: all
  become: true
  vars:
    user: "asdf"
    user_home: "/home/{{ user }}"
    pacman:
      - base-devel
      - git
      - wget
      - github-cli
      - btop
      - fish
      - ranger
      - python
      - python-pip
      - curl
      - unzip
      - ripgrep
      - procps
      - gcc
      - nodejs
      - jdk-openjdk
      - clang
      - cmake
      - ninja
      - ttf-jetbrains-mono-nerd
      - tree
      - fastfetch
      - neovim
      - uv

  tasks:
    - name: Debug group_names
      ansible.builtin.debug:
        msg: "Group names for this host: {{ group_names }}"

    - name: Create user {{ user }} if it does not exist
      ansible.builtin.user:
        name: "{{ user }}"
        shell: /usr/bin/fish
        create_home: true
        home: "{{ user_home }}"
        state: present

    - name: Ensure home directory permissions
      ansible.builtin.file:
        path: "{{ user_home }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0700'
        state: directory

    - name: Install packages
      community.general.pacman:
        name: "{{ pacman }}"
        state: present
        update_cache: true
      retries: 3
      delay: 5
      register: pacman_result
      until: pacman_result is success

    - name: Add fish shell configuration to .bashrc
      ansible.builtin.blockinfile:
        path: "{{ user_home }}/.bashrc"
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        block: |
          if [[ $(ps --no-header --pid=$PPID --format=comm) != "fish" && -z "${BASH_EXECUTION_STRING}" ]]; then
            shopt -q login_shell && LOGIN_OPTION='--login' || LOGIN_OPTION=""
            exec /usr/bin/fish $LOGIN_OPTION
          fi
        state: present
        create: true
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
