- name: All hosts up-to-date
  hosts: all
  vars:
    user: "{{ lookup('env', 'USER') }}"
    pfix:
      wine_default:
        path: "/home/{{ user }}/.wine_default"
        pkgs: [fakejapanese]
        exclude_dlls: []
        install: false
        replace: false
        annihilate: false
      wine_serum:
        path: "/home/{{ user }}/.wine_serum"
        pkgs: [gdiplus]
        exclude_dlls: [d2d1]
        install: false
        replace: false
        annihilate: false
      wine32ntashi: #use env WINEPREFIX="/home/asdf/.wine32ntashi" LC_ALL=ja_JP.utf8 wine
        path: "/home/{{ user }}/.wine32ntashi"
        pkgs: [fakejapanese, quartz]
        exclude_dlls: []
        install: false
        replace: false
        annihilate: false
      wine_stk2:
        path: "/home/{{ user }}/.wine_stk2"
        pkgs: [vkd3d, dxvk]
        exclude_dlls: []
        install: false
        replace: false
        annihilate: false

  tasks:
    - name: Check if prefix path exists and is a directory
      ansible.builtin.stat:
        path: "{{ item.value.path }}"
      register: prefix_stats
      loop: "{{ pfix | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Annihilate prefix when annihilate true and path is dir
      ansible.builtin.shell: winetricks -f -q annihilate
      environment:
        WINEPREFIX: "{{ item.0.value.path }}"
      when:
        - item.0.value.annihilate
        - item.1.stat.isdir | default(false)
      loop: "{{ pfix | dict2items | zip(prefix_stats.results) | list }}"
      loop_control:
        label: "{{ item.0.key }}"

    - name: Run wineboot
      ansible.builtin.shell: wineboot
      environment:
        WINEPREFIX: "{{ item.value.path }}"
      when: item.value.install and not item.value.annihilate
      loop: "{{ pfix | dict2items }}"

    - name: Install packages with winetricks
      ansible.builtin.shell: "winetricks {{ item.1 }}"
      environment:
        WINEPREFIX: "{{ item.0.value.path }}"
      when:
        - item.0.value.install and not item.0.value.annihilate
        - item.1 is defined and item.1|length > 0
      loop: "{{ pfix | dict2items | subelements('value.pkgs', skip_missing=True) }}"
      loop_control:
        label: "{{ item.0.key }}"

    - name: Disable selected packages with winetricks
      ansible.builtin.shell: "winetricks {{ item.1 }}=disabled"
      environment:
        WINEPREFIX: "{{ item.0.value.path }}"
      loop: "{{ pfix | dict2items | subelements('value.exclude_dlls', skip_missing=True) }}"
      when:
        - item.0.value.install and not item.0.value.annihilate
        - item.1 is defined and item.1|length > 0

    - name: replace duplicate wine files to symbolic links
      shell: |
        MONO_SRC_DIR="{{ item.value.path }}/drive_c/windows/mono/mono-2.0"
        MONO_DST_DIR="{{ pfix.default.path }}/drive_c/windows/mono/mono-2.0"
        SYS_SRC_DIR="{{ item.value.path }}/drive_c/windows/system32"
        SYS_DST_DIR="{{ pfix.default.path }}/drive_c/windows/system32"
        FONT_SRC_DIR="{{ item.value.path }}/drive_c/windows/Fonts/"
        FONT_DST_DIR="{{ pfix.default.path }}/drive_c/windows/Fonts/"

        rm "{{ item.value.path }}"/drive_c/windows/Installer/*
        rm "{{ pfix.default.path }}"/drive_c/windows/Installer/*

        mkdir -p "$MONO_DST_DIR"
        mkdir -p "$SYS_DST_DIR"
        mkdir -p "$FONT_DST_DIR"

        find "$MONO_SRC_DIR" -type f -not -type l | while read -r file; do
          REL_PATH="${file#$MONO_SRC_DIR/}"
          DST_FILE="$MONO_DST_DIR/$REL_PATH"
          mkdir -p "$(dirname "$DST_FILE")"
          if [ ! -f "$DST_FILE" ] || cmp -s "$file" "$DST_FILE"; then
            cp -p "$file" "$DST_FILE"
            rm "$file"
            ln -s "$DST_FILE" "$file"
            echo "Processed (mono): $file -> $DST_FILE"
          else
            echo "Skipped (mono): $file (not identical to $DST_FILE)"
          fi
        done

        find "$SYS_SRC_DIR" -maxdepth 1 -type f -not -type l | while read -r file; do
          FILENAME=$(basename "$file")
          DST_FILE="$SYS_DST_DIR/$FILENAME"
          if [ ! -f "$DST_FILE" ] || cmp -s "$file" "$DST_FILE"; then
            cp -p "$file" "$DST_FILE"
            rm "$file"
            ln -s "$DST_FILE" "$file"
            echo "Processed (system32): $file -> $DST_FILE"
          else
            echo "Skipped (system32): $file (not identical to $DST_FILE)"
          fi
        done

        find "$FONT_SRC_DIR" -maxdepth 1 -type f -not -type l | while read -r file; do
          FILENAME=$(basename "$file")
          DST_FILE="$FONT_DST_DIR/$FILENAME"
          if [ ! -f "$DST_FILE" ] || cmp -s "$file" "$DST_FILE"; then
            cp -p "$file" "$DST_FILE"
            rm "$file"
            ln -s "$DST_FILE" "$file"
            echo "Processed font: $file -> $DST_FILE"
          else
            echo "Skipped font: $file (not identical to $DST_FILE)"
          fi
        done

        echo "All files processed."
      loop: "{{ pfix | dict2items }}"
      when: item.value.replace
      args:
        executable: /bin/bash
