---
- hosts: localhost
  gather_facts: no
  vars:
    user: asdf
    pfix:
      wine:
        path: "/home/{{ user }}/.wine"
        pkg: [fakejapanese]
        replace: false
        annihilate: true
        re_install: false
      wine_daw:
        path: "/home/{{ user }}/.wine_daw"
        pkg: [gdiplus, a]
        replace: false
        annihilate: true
        re_install: false

  tasks:
    - name: winetricks.log の内容を読み込み
      ansible.builtin.slurp:
        src: "{{ pfix.wine_daw.path }}/winetricks.log"
      register: wine_daw_log

    - name: ログ内容をリスト化
      set_fact:
        wine_daw_log_list: "{{ (wine_daw_log.content | b64decode).splitlines() }}"

    - name: デバッグログを出力（差異がある場合のみ）
      ansible.builtin.debug:
        msg:
          - "ログの内容: {{ wine_daw_log_list }}"
          - "定義されたパッケージ: {{ pfix.wine_daw.pkg }}"
      when: wine_daw_log_list | difference(pfix.wine_daw.pkg) | length > 0
            or pfix.wine_daw.pkg | difference(wine_daw_log_list) | length > 0

